

## **Homework Problem : Build a classification model for identifying 9 as a digit and 2 as a digit and rest as other class...**


In [113]:
import tensorflow as tf

In [114]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [115]:
from tensorflow import keras

In [116]:
from keras.datasets import mnist

In [117]:
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [118]:
print('Train Images shape:',train_images.shape)
print('Train Labels shape:',train_labels.shape)
print('Test Images shape:',test_images.shape)
print('Test Labels shape:',test_labels.shape)

Train Images shape: (60000, 28, 28)
Train Labels shape: (60000,)
Test Images shape: (10000, 28, 28)
Test Labels shape: (10000,)


In [119]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28)) 
test_images = test_images.astype('float32') / 255

In [120]:
import numpy as np

## **We will assign for 9 = 1 , for 2 = 2 and rest as 0**:



In [121]:
train_labels_new = np.where(train_labels == 9,1,(np.where(train_labels == 2,2,0)))

In [122]:
print(train_labels[:20])
print(train_labels_new[:20])

[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
[0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 2 0 0 1]


In [123]:
test_labels_new = np.where(test_labels == 9,1,(np.where(test_labels == 2,2,0)))

In [124]:
print(test_labels[:20])
print(test_labels_new[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[0 2 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0]


In [125]:
from keras.utils import to_categorical
train_labels_m = to_categorical(train_labels_new)
test_labels_m = to_categorical(test_labels_new)

In [126]:
test_labels_m[:10]

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [127]:
print(train_labels_m.shape)
print(test_labels_m.shape)

(60000, 3)
(10000, 3)


In [128]:
from keras import models
from keras import layers

In [129]:
model_A = keras.models.Sequential([
 keras.layers.Dense(units=150, input_shape=(28 * 28,), activation='relu'),
 keras.layers.Dense(units=100, activation='relu'),
 keras.layers.Dense(units=50, activation='relu'),
 keras.layers.Dense(units=10, activation='relu'),
 keras.layers.Dense(units=3, activation='softmax'),
 ])

In [130]:
model_A.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_25 (Dense)            (None, 150)               117750    
                                                                 
 dense_26 (Dense)            (None, 100)               15100     
                                                                 
 dense_27 (Dense)            (None, 50)                5050      
                                                                 
 dense_28 (Dense)            (None, 10)                510       
                                                                 
 dense_29 (Dense)            (None, 3)                 33        
                                                                 
Total params: 138,443
Trainable params: 138,443
Non-trainable params: 0
_________________________________________________________________


In [131]:
model_A.compile(loss='categorical_crossentropy', optimizer = keras.optimizers.SGD(learning_rate=0.01), metrics=['accuracy'])

In [132]:
model_A.fit(train_images, train_labels_m,epochs=10,batch_size=512,validation_data=(test_images,test_labels_m))

Epoch 1/10
118/118 [==============================] - 3s 20ms/step - loss: 0.6305 - accuracy: 0.7897 - val_loss: 0.5308 - val_accuracy: 0.7959
Epoch 2/10
118/118 [==============================] - 2s 13ms/step - loss: 0.4463 - accuracy: 0.8152 - val_loss: 0.3806 - val_accuracy: 0.8542
Epoch 3/10
118/118 [==============================] - 1s 11ms/step - loss: 0.3199 - accuracy: 0.8896 - val_loss: 0.2743 - val_accuracy: 0.9184
Epoch 4/10
118/118 [==============================] - 1s 11ms/step - loss: 0.2481 - accuracy: 0.9216 - val_loss: 0.2244 - val_accuracy: 0.9283
Epoch 5/10
118/118 [==============================] - 1s 11ms/step - loss: 0.2127 - accuracy: 0.9319 - val_loss: 0.1993 - val_accuracy: 0.9398
Epoch 6/10
118/118 [==============================] - 1s 11ms/step - loss: 0.1919 - accuracy: 0.9380 - val_loss: 0.1830 - val_accuracy: 0.9450
Epoch 7/10
118/118 [==============================] - 1s 11ms/step - loss: 0.1775 - accuracy: 0.9423 - val_loss: 0.1752 - val_accuracy: 0.9468

In [133]:
weights = model_A.get_weights()

In [134]:
weights[0].shape,weights[1].shape,weights[2].shape,weights[3].shape,weights[4].shape,weights[5].shape,weights[6].shape,weights[7].shape,weights[8].shape,weights[9].shape

((784, 150),
 (150,),
 (150, 100),
 (100,),
 (100, 50),
 (50,),
 (50, 10),
 (10,),
 (10, 3),
 (3,))

In [135]:
y_predict = model_A.predict(test_images)
y_predict = np.round(y_predict,3)
y_predict[:8]

313/313 [==============================] - 1s 2ms/step


array([[0.996, 0.001, 0.003],
       [0.328, 0.001, 0.671],
       [0.983, 0.004, 0.013],
       [0.999, 0.   , 0.001],
       [0.903, 0.081, 0.017],
       [0.991, 0.003, 0.006],
       [0.997, 0.003, 0.   ],
       [0.175, 0.816, 0.009]], dtype=float32)

In [136]:
y_predict = y_predict.argmax(axis=1)

y_predict

array([0, 2, 0, ..., 0, 0, 0])

In [137]:
y_predict[:30]

array([0, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
test_labels_new[:30]

array([0, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [139]:
test_labels[:20]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4],
      dtype=uint8)

In [140]:
model_A.evaluate(test_images,test_labels_m)

313/313 [==============================] - 1s 2ms/step - loss: 0.1478 - accuracy: 0.9552


[0.14781220257282257, 0.9552000164985657]