
<p><h3><b><font color = 'DarkBlue'> Setting up Tensorflow </font></b></h3></p>

In [ ]:
%tensorflow_version 2.x
from tensorflow import keras 

TensorFlow 2.x selected.


In [ ]:
#import tensorflow as tf

In [ ]:
#tf.__version__

In [ ]:
model 1 -> 100 rows of data --> metrics 

20 more rows ---

retrain the model on 120 rows
train the existing model (100 rows) + add knowedlge of 20 rows only ----> This part

100 rows -> Model A - > 3 inputs-> 3 unique parameters -> 3 weights + 1 bias
20 rows of data -> for that as well - > 3 weights = bias

Train a new model - > Incorportate the learnings of new data -> also adjust weight of previous model + bias



Learning /Updating an existing pretrained model


<p><h3><b><font color = 'DarkBlue'> Load the MNIST dataset </font></b></h3></p>

In [ ]:
from keras.datasets import mnist

Using TensorFlow backend.


In [ ]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
train_labels.shape

(60000,)


<p><h3><b><font color = 'DarkBlue'> Preprocess the train and test images </font></b></h3></p>

In [ ]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28)) 
test_images = test_images.astype('float32') / 255


<p><h3><b><font color = 'DarkBlue'> Creating train and test labels for identifying digit 2.  </font></b></h3></p>

The label is set to 1 for digit 2 otherwise set to 0. 

In [ ]:
train_labels[:20]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9],
      dtype=uint8)

In [ ]:
import numpy as np

In [ ]:
train_labels_new = np.where(train_labels==2,1,0)

In [ ]:
print(train_labels[:20])
print(train_labels_new[:20])

[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0]


In [ ]:
test_labels[:20]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4],
      dtype=uint8)

In [ ]:
test_labels_new = np.where(test_labels==2,1,0)

In [ ]:
print(test_labels[:20])
print(test_labels_new[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]



<p><h3><b><font color = 'DarkBlue'> Converting the train and test labels to categorical  </font></b></h3></p>

This is required to train the model_A which is created and trained for identifying digits from 0 to 9. 

In [ ]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [ ]:
train_labels[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)


<p><h3><b><font color = 'DarkBlue'> Building a model to train MNIST data (0-9) </font></b></h3></p>

In [ ]:
from keras import models
from keras import layers

In [ ]:
model_A = keras.models.Sequential([
 keras.layers.Dense(units=500, input_shape=(28 * 28,), activation='relu'),
 keras.layers.Dense(units=300, activation='relu'),
 keras.layers.Dense(units=300, activation='relu'),
 keras.layers.Dense(units=200, activation='relu'),
 keras.layers.Dense(units=100, activation='relu'),
 keras.layers.Dense(units=10, activation='softmax'),
 ])

In [ ]:
model_A.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 500)               392500    
_________________________________________________________________
dense_1 (Dense)              (None, 300)               150300    
_________________________________________________________________
dense_2 (Dense)              (None, 300)               90300     
_________________________________________________________________
dense_3 (Dense)              (None, 200)               60200     
_________________________________________________________________
dense_4 (Dense)              (None, 100)               20100     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                1010      
Total params: 714,410
Trainable params: 714,410
Non-trainable params: 0
__________________________________________________

In [ ]:
model_A.compile(loss='categorical_crossentropy', optimizer = keras.optimizers.SGD(learning_rate=0.01), metrics=['accuracy'])

In [ ]:
model_A.fit(train_images, train_labels,epochs=10,batch_size=512,validation_data=(test_images,test_labels))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 6s 97us/sample - loss: 2.1860 - accuracy: 0.2422 - val_loss: 2.0129 - val_accuracy: 0.4715
Epoch 2/10
60000/60000 [==============================] - 5s 87us/sample - loss: 1.6930 - accuracy: 0.6037 - val_loss: 1.2714 - val_accuracy: 0.7256
Epoch 3/10
60000/60000 [==============================] - 5s 88us/sample - loss: 0.9704 - accuracy: 0.7736 - val_loss: 0.7149 - val_accuracy: 0.8232
Epoch 4/10
60000/60000 [==============================] - 5s 87us/sample - loss: 0.6115 - accuracy: 0.8433 - val_loss: 0.5067 - val_accuracy: 0.8617
Epoch 5/10
60000/60000 [==============================] - 5s 87us/sample - loss: 0.4720 - accuracy: 0.8729 - val_loss: 0.4321 - val_accuracy: 0.8769
Epoch 6/10
60000/60000 [==============================] - 5s 87us/sample - loss: 0.4046 - accuracy: 0.8881 - val_loss: 0.3794 - val_accuracy: 0.8910
Epoch 7/10
60000/60000 [==============================] 


<p><h3><b><font color = 'DarkBlue'> Save model_A for reuse </font></b></h3></p>

In [ ]:
import os
os.getcwd()
model_A.save("trained_model_A.h5")


<p><h3><b><font color = 'DarkBlue'> Load model_A and create a clone for reuse </font></b></h3></p>

In [ ]:
model_pretrained = keras.models.load_model("trained_model_A.h5")

In [ ]:
model_A_clone = keras.models.clone_model(model_pretrained)
model_A_clone.set_weights(model_pretrained.get_weights())


<p><h3><b><font color = 'DarkBlue'> Build a new model using all the layers of model_A with a new output layer for classifying digit 2 </font></b></h3></p>

In [ ]:
model_new = keras.models.Sequential(model_A_clone.layers[:-1])
model_new.add(keras.layers.Dense(1, activation="sigmoid"))

In [ ]:
model_new.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 500)               392500    
_________________________________________________________________
dense_1 (Dense)              (None, 300)               150300    
_________________________________________________________________
dense_2 (Dense)              (None, 300)               90300     
_________________________________________________________________
dense_3 (Dense)              (None, 200)               60200     
_________________________________________________________________
dense_4 (Dense)              (None, 100)               20100     
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 101       
Total params: 713,501
Trainable params: 713,501
Non-trainable params: 0
________________________________________________

In [ ]:
for layer in model_new.layers[:-1]:         # freeze the reused layers for some epochs giving the new layer some time to learn reasonable weights. 
  layer.trainable = False


<p><h3><b><font color = 'DarkBlue'> Compile new model </font></b></h3></p>

we must compile the model after freeze or unfreeze layers.


In [ ]:
model_new.compile(loss="binary_crossentropy", optimizer="sgd", metrics=["accuracy"])

<p><h3><b><font color = 'DarkBlue'> Fit the new model for classifying digit 2 </font></b></h3></p>

Train model_new for the classifying digit 2 first for few epochs to avoid error. 

In [ ]:
history = model_new.fit(train_images, train_labels_new, epochs=5, batch_size=512, validation_data=(test_images,test_labels_new))

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 48us/sample - loss: 0.2379 - accuracy: 0.9209 - val_loss: 0.1618 - val_accuracy: 0.9562
Epoch 2/5
60000/60000 [==============================] - 2s 40us/sample - loss: 0.1480 - accuracy: 0.9572 - val_loss: 0.1251 - val_accuracy: 0.9658
Epoch 3/5
60000/60000 [==============================] - 2s 38us/sample - loss: 0.1229 - accuracy: 0.9656 - val_loss: 0.1098 - val_accuracy: 0.9702
Epoch 4/5
60000/60000 [==============================] - 2s 41us/sample - loss: 0.1108 - accuracy: 0.9691 - val_loss: 0.1013 - val_accuracy: 0.9731
Epoch 5/5
60000/60000 [==============================] - 2s 40us/sample - loss: 0.1036 - accuracy: 0.9709 - val_loss: 0.0960 - val_accuracy: 0.9734


In [ ]:
for layer in model_new.layers[:-1]:      # unfreeze the reused layers  
  layer.trainable = True

In [ ]:
model_new.compile(loss="binary_crossentropy", optimizer="sgd", metrics=["accuracy"])

In [ ]:
model_new.fit(train_images, train_labels_new, epochs=15, batch_size=512, validation_data=(test_images,test_labels_new))   # fit the new model on the data

Train on 60000 samples, validate on 10000 samples
Epoch 1/15
60000/60000 [==============================] - 6s 94us/sample - loss: 0.0856 - accuracy: 0.9755 - val_loss: 0.0742 - val_accuracy: 0.9780
Epoch 2/15
60000/60000 [==============================] - 5s 86us/sample - loss: 0.0718 - accuracy: 0.9787 - val_loss: 0.0667 - val_accuracy: 0.9808
Epoch 3/15
60000/60000 [==============================] - 5s 84us/sample - loss: 0.0657 - accuracy: 0.9805 - val_loss: 0.0729 - val_accuracy: 0.9772
Epoch 4/15
60000/60000 [==============================] - 5s 86us/sample - loss: 0.0618 - accuracy: 0.9812 - val_loss: 0.0598 - val_accuracy: 0.9836
Epoch 5/15
60000/60000 [==============================] - 5s 87us/sample - loss: 0.0589 - accuracy: 0.9822 - val_loss: 0.0577 - val_accuracy: 0.9839
Epoch 6/15
60000/60000 [==============================] - 5s 88us/sample - loss: 0.0560 - accuracy: 0.9828 - val_loss: 0.0636 - val_accuracy: 0.9810
Epoch 7/15
60000/60000 [==============================] 

In [ ]:
model_new.evaluate(test_images, test_labels_new)      # Evaluate the model on test dataset 

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.04050608561336994, 0.9886]

In [ ]:
y_pred = model_new.predict_classes(test_images)   # predict_classes() outputs the class with highest estimated probability
y_pred=y_pred.flatten()                           # Convert it to 1D array
y_pred                                            # new predicted labels for image 2 as 1 otherwise 0

array([0, 1, 0, ..., 0, 0, 0], dtype=int32)

In [ ]:
test_labels_new[:10]              # displayed actual test labels for comparision

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

<p><h3><b><font color = 'DarkBlue'> Try building models with reusing only first few layers from model_A </font></b></h3></p>

In [ ]:
model_B = keras.models.Sequential(model_A_clone.layers[:-3])
model_B.add(keras.layers.Dense(1, activation="sigmoid"))

In [ ]:
model_B.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 500)               392500    
_________________________________________________________________
dense_1 (Dense)              (None, 300)               150300    
_________________________________________________________________
dense_2 (Dense)              (None, 300)               90300     
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 301       
Total params: 633,401
Trainable params: 633,401
Non-trainable params: 0
_________________________________________________________________


In [ ]:
for layer in model_B.layers[:-1]:         # freeze the reused layers for some epochs giving the new layer some time to learn reasonable weights. 
  layer.trainable = False


<p><h3><b><font color = 'DarkBlue'> Compile new model </font></b></h3></p>

we must compile the model after freeze or unfreeze layers.


In [ ]:
model_B.compile(loss="binary_crossentropy", optimizer="sgd", metrics=["accuracy"])

<p><h3><b><font color = 'DarkBlue'> Fit the new model for classifying digit 2 </font></b></h3></p>

Train model_B for the classifying digit 2 first for few epochs to avoid error. 

In [ ]:
history = model_B.fit(train_images, train_labels_new, epochs=5, batch_size=512, validation_data=(test_images,test_labels_new))

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 43us/sample - loss: 0.2710 - accuracy: 0.9013 - val_loss: 0.2008 - val_accuracy: 0.9020
Epoch 2/5
60000/60000 [==============================] - 2s 35us/sample - loss: 0.1656 - accuracy: 0.9362 - val_loss: 0.1402 - val_accuracy: 0.9634
Epoch 3/5
60000/60000 [==============================] - 2s 34us/sample - loss: 0.1259 - accuracy: 0.9633 - val_loss: 0.1129 - val_accuracy: 0.9713
Epoch 4/5
60000/60000 [==============================] - 2s 34us/sample - loss: 0.1058 - accuracy: 0.9719 - val_loss: 0.0979 - val_accuracy: 0.9749
Epoch 5/5
60000/60000 [==============================] - 2s 34us/sample - loss: 0.0937 - accuracy: 0.9758 - val_loss: 0.0883 - val_accuracy: 0.9770


In [ ]:
for layer in model_B.layers[:-1]:      # unfreeze the reused layers  
  layer.trainable = True

In [ ]:
model_B.compile(loss="binary_crossentropy", optimizer="sgd", metrics=["accuracy"])

In [ ]:
model_B.fit(train_images, train_labels_new, epochs=15, batch_size=512, validation_data=(test_images,test_labels_new))   # fit the new model on the data

Train on 60000 samples, validate on 10000 samples
Epoch 1/15
60000/60000 [==============================] - 5s 85us/sample - loss: 0.0748 - accuracy: 0.9810 - val_loss: 0.0674 - val_accuracy: 0.9807
Epoch 2/15
60000/60000 [==============================] - 5s 77us/sample - loss: 0.0616 - accuracy: 0.9832 - val_loss: 0.0587 - val_accuracy: 0.9852
Epoch 3/15
60000/60000 [==============================] - 5s 77us/sample - loss: 0.0561 - accuracy: 0.9843 - val_loss: 0.0552 - val_accuracy: 0.9857
Epoch 4/15
60000/60000 [==============================] - 4s 75us/sample - loss: 0.0529 - accuracy: 0.9851 - val_loss: 0.0529 - val_accuracy: 0.9859
Epoch 5/15
60000/60000 [==============================] - 5s 77us/sample - loss: 0.0505 - accuracy: 0.9856 - val_loss: 0.0508 - val_accuracy: 0.9869
Epoch 6/15
60000/60000 [==============================] - 5s 77us/sample - loss: 0.0486 - accuracy: 0.9859 - val_loss: 0.0510 - val_accuracy: 0.9859
Epoch 7/15
60000/60000 [==============================] 

In [ ]:
model_B.evaluate(test_images, test_labels_new)      # Evaluate the model on test dataset 

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.04245396930351853, 0.9878]

In [ ]:
y_pred = model_B.predict_classes(test_images)   # predict_classes() outputs the class with highest estimated probability
y_pred=y_pred.flatten()                           # Convert it to 1D array
y_pred                                            # new predicted labels for image 2 as 1 otherwise 0

array([0, 1, 0, ..., 0, 0, 0], dtype=int32)

In [ ]:
test_labels_new[:10]              # displayed actual test labels for comparision

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])